### ISSUE TITLE
Face detected, but not have photo

### ISSUE THREAD

**Issue by SpringlesMcOutrage** [robotzero1/esp32cam-selfiecam#1]
.....Ready! Use 'http://192.168.100.201' to connect

Initialisation done.

Listing SPIFFS files:
=================================================
  File name                              Size
=================================================
  /_count1.jpg                           5491 bytes
  /_count2.jpg                           6996 bytes
  /_count3.jpg                           7706 bytes
=================================================

CORRUPT HEAP: Bad head at 0x3ffde37c. Expected 0xabba1234 got 0x00000008
abort() was called at PC 0x4008a5fd on core 1

ELF file SHA256: 0000000000000000

Backtrace: 0x4008e228:0x3ffb1b10 0x4008e4a1:0x3ffb1b30 0x4008a5fd:0x3ffb1b50 0x4008a729:0x3ffb1b80 0x4010759b:0x3ffb1ba0 0x40103075:0x3ffb1e60 0x40102f65:0x3ffb1eb0 0x400937f1:0x3ffb1ee0 0x400828d2:0x3ffb1f00 0x4008a4f5:0x3ffb1f20 0x4000bec7:0x3ffb1f40 0x400d1780:0x3ffb1f60 0x400d21cf:0x3ffb1f80 0x400e1f71:0x3ffb1fb0 0x40090132:0x3ffb1fd0

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:10944
load:0x40080400,len:6388
entry 0x400806b4
.....Ready! Use 'http://192.168.100.201' to connect

This is text from serial monitor
Whot i must to do?

**Comment by robotzero1** [comment]
Which version of the ESP32 Hardware Library do you have installed?

**Comment by SpringlesMcOutrage** [comment]
> Which version of the ESP32 Hardware Library do you have installed?
1.0.6, latest

**Comment by robotzero1** [comment]
I'm guessing but maybe the partition system is different in 1.0.6. Can you try 1.0.4 or .5?

**Comment by SpringlesMcOutrage** [comment]
In 1.0.4 not connecting to wifi, on .5 aslo -> 
CORRUPT HEAP: Bad head at 0x3ffdd014. Expected 0xabba1234 got 0x00000008
abort() was called at PC 0x40088ba1 on core 1

ELF file SHA256: 0000000000000000

Backtrace: 0x4008e228:0x3ffb1b10 0x4008e4a1:0x3ffb1b30 0x40088ba1:0x3ffb1b50 0x40088ccd:0x3ffb1b80 0x400ea233:0x3ffb1ba0 0x400e5d6d:0x3ffb1e60 0x400e5c6c:0x3ffb1eb0 0x400937cd:0x3ffb1ee0 0x400892e2:0x3ffb1f00 0x40088a99:0x3ffb1f20 0x4000bec7:0x3ffb1f40 0x400d1ac5:0x3ffb1f60 0x400d2527:0x3ffb1f80 0x400e20e5:0x3ffb1fb0 0x40090122:0x3ffb1fd0

**Comment by robotzero1** [comment]
The Wi-Fi part is pretty standard. Should work in 1.0.4. Do you see a line of dots appearing in the serial monitor?

**Comment by SpringlesMcOutrage** [comment]
No i nothing see at 1.0.4(full white screen and if i reset nothing not do)

**Comment by SpringlesMcOutrage** [comment]
Maybe can you send all library which you used, becouse some library as JPEGDecoder or AsyncTCP you dont write in tutorial

**Comment by robotzero1** [comment]
From the resources section these should be what you need:

Async Webserver Docs: https://github.com/me-no-dev/ESPAsyncWebServer
TFT Library: https://github.com/Bodmer/TFT_eSPI
TFT Extras Library: https://github.com/Bodmer/TFT_eFEX

**Comment by SpringlesMcOutrage** [comment]
if i download only this librarys->  i have error (multiple 'wifi.h')

**Comment by robotzero1** [comment]
Does it stop the flashing progress? It's 'normal' to see multiple wifi, the compiler will pick one for you.

**Comment by SpringlesMcOutrage** [comment]
Yes it stop and have this error
Multiple libraries were found for "WiFi.h"
In file included from C:\Users\romka\OneDrive\Документы\Arduino\SelfieCam\SelfieCam.ino:1:0:
Used: C:\Users\romka\OneDrive\Документы\ArduinoData\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
Not used: C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.57.0_x86__mdqgnx93n4wtt\libraries\WiFi
C:\Users\romka\OneDrive\���������\Arduino\libraries\ESPAsyncWebServer-master\src/ESPAsyncWebServer.h:33:22: fatal error: AsyncTCP.h: No such file or directory
compilation terminated.
exit status 1
Error compiling for board ESP32 Dev Module.

and i solve this error simply download AsyncTCP lybrary, which you don`t write

**Comment by robotzero1** [comment]
Ah, OK.. the fatal error was the missing AsyncTCP library. It mentions this at the top of the instructions for the ESPAsyncWebServer installation but I should add it to the tutorial.

**Comment by SpringlesMcOutrage** [comment]
Now you can say all librarys?

**Comment by SpringlesMcOutrage** [comment]
I work third day and im if realy very angry on esp

**Comment by SpringlesMcOutrage** [comment]
Hah i do this problem. You need in file selficam made
from this 
free(net_boxes->score);
free(net_boxes->box);
free(net_boxes->landmark);
free(net_boxes);
to this
dl_lib_free(net_boxes->score);
dl_lib_free(net_boxes->box);
dl_lib_free(net_boxes->landmark);
dl_lib_free(net_boxes);

**Comment by SpringlesMcOutrage** [comment]
but i have enother problem
[E][esp_jpg_decode.c:118] esp_jpg_decode(): JPG Decompression Failed! Data format error

**Comment by SpringlesMcOutrage** [comment]
I close this issue. So you know. 1 library. 2 Non working cod
